### ISSUE TITLE
undefined method `serializer' for #<ActiveModel::Serializer::Association:0x007f5bec8b30e0>

### ISSUE THREAD

**Issue by adavia** [codenoble/active_model_normalizr#1]
Is this gem being maintained?
Im getting the following error

```ruby
{
    "status": 500,
    "error": "Internal Server Error",
    "exception": "#<NoMethodError: undefined method `serializer' for #<ActiveModel::Serializer::Association:0x007f5bec8b30e0>\nDid you mean?  serializable_hash>",
    "traces": {
        "Application Trace": [
            {
                "id": 62,
                "trace": "app/controllers/api/v1/posts_controller.rb:9:in `index'"
            }
        ],
        "Framework Trace": [
            {
                "id": 0,
                "trace": "active_model_normalizr (1.0.0) lib/active_model_serializers/adapter/normalizr.rb:58:in `block (2 levels) in entities'"
            },
            {
                "id": 1,
                "trace": "active_model_serializers (0.10.6) lib/active_model/serializer.rb:348:in `yield'"
            },
            {
                "id": 2,
                "trace": "active_model_serializers (0.10.6) lib/active_model/serializer.rb:348:in `block (2 levels) in associations'"
            },
            {
         ]
     }
}
```

**Comment by adamcrown** [comment]
@adavia It is being maintained but I've been pretty busy recently and don't have as much time as I'd like for my open source projects anymore. I'm hoping that will change in a few months at least.

I'd imagine this is an Active Model Serializer incompatibility with newer versions. They have had a history of making a lot of breaking changes. I'll do my best to come up with a fix.

What version of the `active_model_serializers` gem were you using when you got this error.

Also, sorry for the long delay in responding.
